AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for Nested Stacks

Resources:
      
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/kalyani-shah/cloudform/blob/main/vpc.yml

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
    Properties:
      TemplateURL: https://github.com/kalyani-shah/cloudform/blob/main/ec2.yml


  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EC2Stack    # EC2Stack is a dependency for RDSStack
    Properties:
      TemplateURL: https://github.com/kalyani-shah/cloudform/blob/main/rds.yml

  
  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EC2Stack  
    Properties:
        TemplateURL: https://github.com/kalyani-shah/cloudform/blob/main/lb.yml
 

 
